In [4]:
import pandas as pd

df = pd.read_csv("Students_exams_cols_cleanup.csv")
df.head()

   Gender  Math Score  Reading Score  Writing Score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [5]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, Gender='female', _2=72, _3=72, _4=74)
Pandas(Index=1, Gender='female', _2=69, _3=90, _4=88)
Pandas(Index=2, Gender='female', _2=90, _3=95, _4=93)
Pandas(Index=3, Gender='male', _2=47, _3=57, _4=44)
Pandas(Index=4, Gender='male', _2=76, _3=78, _4=75)
Pandas(Index=5, Gender='female', _2=71, _3=83, _4=78)
Pandas(Index=6, Gender='female', _2=88, _3=95, _4=92)
Pandas(Index=7, Gender='male', _2=40, _3=43, _4=39)
Pandas(Index=8, Gender='male', _2=64, _3=64, _4=67)
Pandas(Index=9, Gender='female', _2=38, _3=60, _4=50)
Pandas(Index=10, Gender='male', _2=58, _3=54, _4=52)
Pandas(Index=11, Gender='male', _2=40, _3=52, _4=43)
Pandas(Index=12, Gender='female', _2=65, _3=81, _4=73)
Pandas(Index=13, Gender='male', _2=78, _3=72, _4=70)
Pandas(Index=14, Gender='female', _2=50, _3=53, _4=58)
Pandas(Index=15, Gender='female', _2=69, _3=75, _4=78)
Pandas(Index=16, Gender='male', _2=88, _3=89, _4=86)
Pandas(Index=17, Gender='female', _2=18, _3=32, _4=28)
Pandas(Index=18, Gender='male', _2=46, _3=42, _4=46)
Pandas(Index=19, Gender='female', _2=54, _3=58, _4=61)
Pandas(Index=20, Gender='male', _2=66, _3=69, _4=63)
Pandas(Index=21, Gender='female', _2=65, _3=75, _4=70)
Pandas(Index=22, Gender='male', _2=44, _3=54, _4=53)
Pandas(Index=23, Gender='female', _2=69, _3=73, _4=73)
Pandas(Index=24, Gender='male', _2=74, _3=71, _4=80)
Pandas(Index=25, Gender='male', _2=73, _3=74, _4=72)
Pandas(Index=26, Gender='male', _2=69, _3=54, _4=55)
Pandas(Index=27, Gender='female', _2=67, _3=69, _4=75)
Pandas(Index=28, Gender='male', _2=70, _3=70, _4=65)
Pandas(Index=29, Gender='female', _2=62, _3=70, _4=75)
Pandas(Index=30, Gender='female', _2=69, _3=74, _4=74)
Pandas(Index=31, Gender='female', _2=63, _3=65, _4=61)
Pandas(Index=32, Gender='female', _2=56, _3=72, _4=65)
Pandas(Index=33, Gender='male', _2=40, _3=42, _4=38)
Pandas(Index=34, Gender='male', _2=97, _3=87, _4=82)
Pandas(Index=35, Gender='male', _2=81, _3=81, _4=79)
Pandas(Index=36, Gender='female', _2=74, _3=81, _4=83)
Pandas(Index=37, Gender='female', _2=50, _3=64, _4=59)
Pandas(Index=38, Gender='female', _2=75, _3=90, _4=88)
Pandas(Index=39, Gender='male', _2=57, _3=56, _4=57)
Pandas(Index=40, Gender='male', _2=55, _3=61, _4=54)
Pandas(Index=41, Gender='female', _2=58, _3=73, _4=68)
Pandas(Index=42, Gender='female', _2=53, _3=58, _4=65)
Pandas(Index=43, Gender='male', _2=59, _3=65, _4=66)
Pandas(Index=44, Gender='female', _2=50, _3=56, _4=54)
Pandas(Index=45, Gender='male', _2=65, _3=54, _4=57)
Pandas(Index=46, Gender='female', _2=55, _3=65, _4=62)
Pandas(Index=47, Gender='female', _2=66, _3=71, _4=76)
Pandas(Index=48, Gender='female', _2=57, _3=74, _4=76)
Pandas(Index=49, Gender='male', _2=82, _3=84, _4=82)
Pandas(Index=50, Gender='male', _2=53, _3=55, _4=48)
Pandas(Index=51, Gender='male', _2=77, _3=69, _4=68)
Pandas(Index=52, Gender='male', _2=53, _3=44, _4=42)
Pandas(Index=53, Gender='male', _2=88, _3=78, _4=75)
Pandas(Index=54, Gender='female', _2=71, _3=84, _4=87)
Pandas(Index=55, Gender='female', _2=33, _3=41, _4=43)
Pandas(Index=56, Gender='female', _2=82, _3=85, _4=86)
Pandas(Index=57, Gender='male', _2=52, _3=55, _4=49)
Pandas(Index=58, Gender='male', _2=58, _3=59, _4=58)
Pandas(Index=59, Gender='female', _2=0, _3=17, _4=10)
Pandas(Index=60, Gender='male', _2=79, _3=74, _4=72)
Pandas(Index=61, Gender='male', _2=39, _3=39, _4=34)
Pandas(Index=62, Gender='male', _2=62, _3=61, _4=55)
Pandas(Index=63, Gender='female', _2=69, _3=80, _4=71)
Pandas(Index=64, Gender='female', _2=59, _3=58, _4=59)
Pandas(Index=65, Gender='male', _2=67, _3=64, _4=61)
Pandas(Index=66, Gender='male', _2=45, _3=37, _4=37)
Pandas(Index=67, Gender='female', _2=60, _3=72, _4=74)
Pandas(Index=68, Gender='male', _2=61, _3=58, _4=56)
Pandas(Index=69, Gender='female', _2=39, _3=64, _4=57)
Pandas(Index=70, Gender='female', _2=58, _3=63, _4=73)
Pandas(Index=71, Gender='male', _2=63, _3=55, _4=63)
Pandas(Index=72, Gender='female', _2=41, _3=51, _4=48)
Pandas(Index=73, Gender='male', _2=61, _3=57, _4=56)
Pandas(Index=74, Gender='male', _2=49, _3=49, _4=41)
Pandas(Index=75, Gender='male', _2=44, _3=41, _4=38)
Pandas(Index=76, Gender='male', _2=30, _3=26, _4=22)
Pandas(Index=77, Gender='male', _2=80, _3=78, _4=81)
Pandas(Index=78, Gender='female', _2=61, _3=74, _4=72)
Pandas(Index=79, Gender='female', _2=62, _3=68, _4=68)
Pandas(Index=80, Gender='female', _2=47, _3=49, _4=50)
Pandas(Index=81, Gender='male', _2=49, _3=45, _4=45)
Pandas(Index=82, Gender='male', _2=50, _3=47, _4=54)
Pandas(Index=83, Gender='male', _2=72, _3=64, _4=63)
Pandas(Index=84, Gender='male', _2=42, _3=39, _4=34)
Pandas(Index=85, Gender='female', _2=73, _3=80, _4=82)
Pandas(Index=86, Gender='female', _2=76, _3=83, _4=88)
Pandas(Index=87, Gender='female', _2=71, _3=71, _4=74)
Pandas(Index=88, Gender='female', _2=58, _3=70, _4=67)
Pandas(Index=89, Gender='female', _2=73, _3=86, _4=82)
Pandas(Index=90, Gender='female', _2=65, _3=72, _4=74)
Pandas(Index=91, Gender='male', _2=27, _3=34, _4=36)
Pandas(Index=92, Gender='male', _2=71, _3=79, _4=71)
Pandas(Index=93, Gender='male', _2=43, _3=45, _4=50)
Pandas(Index=94, Gender='female', _2=79, _3=86, _4=92)
Pandas(Index=95, Gender='male', _2=78, _3=81, _4=82)
Pandas(Index=96, Gender='male', _2=65, _3=66, _4=62)
Pandas(Index=97, Gender='female', _2=63, _3=72, _4=70)
Pandas(Index=98, Gender='female', _2=58, _3=67, _4=62)
Pandas(Index=99, Gender='female', _2=65, _3=67, _4=62)
Pandas(Index=100, Gender='male', _2=79, _3=67, _4=67)
Pandas(Index=101, Gender='male', _2=68, _3=74, _4=74)
Pandas(Index=102, Gender='female', _2=85, _3=91, _4=89)
Pandas(Index=103, Gender='male', _2=60, _3=44, _4=47)
Pandas(Index=104, Gender='male', _2=98, _3=86, _4=90)
Pandas(Index=105, Gender='female', _2=58, _3=67, _4=72)
Pandas(Index=106, Gender='female', _2=87, _3=100, _4=100)
Pandas(Index=107, Gender='male', _2=66, _3=63, _4=64)
Pandas(Index=108, Gender='female', _2=52, _3=76, _4=70)
Pandas(Index=109, Gender='female', _2=70, _3=64, _4=72)
Pandas(Index=110, Gender='female', _2=77, _3=89, _4=98)
Pandas(Index=111, Gender='male', _2=62, _3=55, _4=49)
Pandas(Index=112, Gender='male', _2=54, _3=53, _4=47)
Pandas(Index=113, Gender='female', _2=51, _3=58, _4=54)
Pandas(Index=114, Gender='female', _2=99, _3=100, _4=100)
Pandas(Index=115, Gender='male', _2=84, _3=77, _4=74)
Pandas(Index=116, Gender='female', _2=75, _3=85, _4=82)
Pandas(Index=117, Gender='female', _2=78, _3=82, _4=79)
Pandas(Index=118, Gender='female', _2=51, _3=63, _4=61)
Pandas(Index=119, Gender='female', _2=55, _3=69, _4=65)
Pandas(Index=120, Gender='female', _2=79, _3=92, _4=89)
Pandas(Index=121, Gender='male', _2=91, _3=89, _4=92)
Pandas(Index=122, Gender='female', _2=88, _3=93, _4=93)
Pandas(Index=123, Gender='male', _2=63, _3=57, _4=56)
Pandas(Index=124, Gender='male', _2=83, _3=80, _4=73)
Pandas(Index=125, Gender='female', _2=87, _3=95, _4=86)
Pandas(Index=126, Gender='male', _2=72, _3=68, _4=67)
Pandas(Index=127, Gender='male', _2=65, _3=77, _4=74)
Pandas(Index=128, Gender='male', _2=82, _3=82, _4=74)
Pandas(Index=129, Gender='female', _2=51, _3=49, _4=51)
Pandas(Index=130, Gender='male', _2=89, _3=84, _4=82)
Pandas(Index=131, Gender='male', _2=53, _3=37, _4=40)
Pandas(Index=132, Gender='male', _2=87, _3=74, _4=70)
Pandas(Index=133, Gender='female', _2=75, _3=81, _4=84)
Pandas(Index=134, Gender='male', _2=74, _3=79, _4=75)
Pandas(Index=135, Gender='male', _2=58, _3=55, _4=48)
Pandas(Index=136, Gender='male', _2=51, _3=54, _4=41)
Pandas(Index=137, Gender='male', _2=70, _3=55, _4=56)
Pandas(Index=138, Gender='female', _2=59, _3=66, _4=67)
Pandas(Index=139, Gender='male', _2=71, _3=61, _4=69)
Pandas(Index=140, Gender='female', _2=76, _3=72, _4=71)
Pandas(Index=141, Gender='female', _2=59, _3=62, _4=64)
Pandas(Index=142, Gender='female', _2=42, _3=55, _4=54)
Pandas(Index=143, Gender='male', _2=57, _3=43, _4=47)
Pandas(Index=144, Gender='male', _2=88, _3=73, _4=78)
Pandas(Index=145, Gender='female', _2=22, _3=39, _4=33)
Pandas(Index=146, Gender='male', _2=88, _3=84, _4=75)
Pandas(Index=147, Gender='male', _2=73, _3=68, _4=66)
Pandas(Index=148, Gender='female', _2=68, _3=75, _4=81)
Pandas(Index=149, Gender='male', _2=100, _3=100, _4=93)
Pandas(Index=150, Gender='male', _2=62, _3=67, _4=69)
Pandas(Index=151, Gender='male', _2=77, _3=67, _4=68)
Pandas(Index=152, Gender='female', _2=59, _3=70, _4=66)
Pandas(Index=153, Gender='male', _2=54, _3=49, _4=47)
Pandas(Index=154, Gender='male', _2=62, _3=67, _4=61)
Pandas(Index=155, Gender='female', _2=70, _3=89, _4=88)
Pandas(Index=156, Gender='female', _2=66, _3=74, _4=78)
Pandas(Index=157, Gender='male', _2=60, _3=60, _4=60)
Pandas(Index=158, Gender='female', _2=61, _3=86, _4=87)
Pandas(Index=159, Gender='male', _2=66, _3=62, _4=64)
Pandas(Index=160, Gender='male', _2=82, _3=78, _4=74)
Pandas(Index=161, Gender='female', _2=75, _3=88, _4=85)
Pandas(Index=162, Gender='male', _2=49, _3=53, _4=52)
Pandas(Index=163, Gender='male', _2=52, _3=53, _4=49)
Pandas(Index=164, Gender='female', _2=81, _3=92, _4=91)
Pandas(Index=165, Gender='female', _2=96, _3=100, _4=100)
Pandas(Index=166, Gender='male', _2=53, _3=51, _4=51)
Pandas(Index=167, Gender='female', _2=58, _3=76, _4=78)
Pandas(Index=168, Gender='female', _2=68, _3=83, _4=78)
Pandas(Index=169, Gender='female', _2=67, _3=75, _4=70)
Pandas(Index=170, Gender='male', _2=72, _3=73, _4=74)
Pandas(Index=171, Gender='male', _2=94, _3=88, _4=78)
Pandas(Index=172, Gender='female', _2=79, _3=86, _4=81)
Pandas(Index=173, Gender='female', _2=63, _3=67, _4=70)
Pandas(Index=174, Gender='female', _2=43, _3=51, _4=54)
Pandas(Index=175, Gender='female', _2=81, _3=91, _4=87)
Pandas(Index=176, Gender='female', _2=46, _3=54, _4=58)
Pandas(Index=177, Gender='female', _2=71, _3=77, _4=77)
Pandas(Index=178, Gender='female', _2=52, _3=70, _4=62)
Pandas(Index=179, Gender='female', _2=97, _3=100, _4=100)
Pandas(Index=180, Gender='male', _2=62, _3=68, _4=75)
Pandas(Index=181, Gender='female', _2=46, _3=64, _4=66)
Pandas(Index=182, Gender='female', _2=50, _3=50, _4=47)
Pandas(Index=183, Gender='female', _2=65, _3=69, _4=70)
Pandas(Index=184, Gender='male', _2=45, _3=52, _4=49)
Pandas(Index=185, Gender='male', _2=65, _3=67, _4=65)
Pandas(Index=186, Gender='male', _2=80, _3=76, _4=65)
Pandas(Index=187, Gender='male', _2=62, _3=66, _4=68)
Pandas(Index=188, Gender='male', _2=48, _3=52, _4=45)
Pandas(Index=189, Gender='female', _2=77, _3=88, _4=87)
Pandas(Index=190, Gender='female', _2=66, _3=65, _4=69)
Pandas(Index=191, Gender='male', _2=76, _3=83, _4=79)
Pandas(Index=192, Gender='female', _2=62, _3=64, _4=66)
Pandas(Index=193, Gender='male', _2=77, _3=62, _4=62)
Pandas(Index=194, Gender='female', _2=69, _3=84, _4=85)
Pandas(Index=195, Gender='male', _2=61, _3=55, _4=52)
Pandas(Index=196, Gender='male', _2=59, _3=69, _4=65)
Pandas(Index=197, Gender='male', _2=55, _3=56, _4=51)
Pandas(Index=198, Gender='female', _2=45, _3=53, _4=55)
Pandas(Index=199, Gender='female', _2=78, _3=79, _4=76)
Pandas(Index=200, Gender='female', _2=67, _3=84, _4=86)
Pandas(Index=201, Gender='female', _2=65, _3=81, _4=77)
Pandas(Index=202, Gender='male', _2=69, _3=77, _4=69)
Pandas(Index=203, Gender='female', _2=57, _3=69, _4=68)
Pandas(Index=204, Gender='male', _2=59, _3=41, _4=42)
Pandas(Index=205, Gender='male', _2=74, _3=71, _4=78)
Pandas(Index=206, Gender='male', _2=82, _3=62, _4=62)
Pandas(Index=207, Gender='male', _2=81, _3=80, _4=76)
Pandas(Index=208, Gender='female', _2=74, _3=81, _4=76)
Pandas(Index=209, Gender='female', _2=58, _3=61, _4=66)
Pandas(Index=210, Gender='male', _2=80, _3=79, _4=79)
Pandas(Index=211, Gender='male', _2=35, _3=28, _4=27)
Pandas(Index=212, Gender='female', _2=42, _3=62, _4=60)
Pandas(Index=213, Gender='male', _2=60, _3=51, _4=56)
Pandas(Index=214, Gender='male', _2=87, _3=91, _4=81)
Pandas(Index=215, Gender='male', _2=84, _3=83, _4=75)
Pandas(Index=216, Gender='female', _2=83, _3=86, _4=88)
Pandas(Index=217, Gender='female', _2=34, _3=42, _4=39)
Pandas(Index=218, Gender='male', _2=66, _3=77, _4=70)
Pandas(Index=219, Gender='male', _2=61, _3=56, _4=56)
Pandas(Index=220, Gender='female', _2=56, _3=68, _4=74)
Pandas(Index=221, Gender='male', _2=87, _3=85, _4=73)
Pandas(Index=222, Gender='female', _2=55, _3=65, _4=62)
Pandas(Index=223, Gender='male', _2=86, _3=80, _4=75)
Pandas(Index=224, Gender='female', _2=52, _3=66, _4=73)
Pandas(Index=225, Gender='female', _2=45, _3=56, _4=54)
Pandas(Index=226, Gender='female', _2=72, _3=72, _4=71)
Pandas(Index=227, Gender='male', _2=57, _3=50, _4=54)
Pandas(Index=228, Gender='male', _2=68, _3=72, _4=64)
Pandas(Index=229, Gender='female', _2=88, _3=95, _4=94)
Pandas(Index=230, Gender='male', _2=76, _3=64, _4=66)
Pandas(Index=231, Gender='male', _2=46, _3=43, _4=42)
Pandas(Index=232, Gender='female', _2=67, _3=86, _4=83)
Pandas(Index=233, Gender='male', _2=92, _3=87, _4=78)
Pandas(Index=234, Gender='male', _2=83, _3=82, _4=84)
Pandas(Index=235, Gender='male', _2=80, _3=75, _4=77)
Pandas(Index=236, Gender='male', _2=63, _3=66, _4=67)
Pandas(Index=237, Gender='female', _2=64, _3=60, _4=74)
Pandas(Index=238, Gender='male', _2=54, _3=52, _4=51)
Pandas(Index=239, Gender='male', _2=84, _3=80, _4=80)
Pandas(Index=240, Gender='male', _2=73, _3=68, _4=66)
Pandas(Index=241, Gender='female', _2=80, _3=83, _4=83)
Pandas(Index=242, Gender='female', _2=56, _3=52, _4=55)
Pandas(Index=243, Gender='male', _2=59, _3=51, _4=43)
Pandas(Index=244, Gender='male', _2=75, _3=74, _4=69)
Pandas(Index=245, Gender='male', _2=85, _3=76, _4=71)
Pandas(Index=246, Gender='male', _2=89, _3=76, _4=74)
Pandas(Index=247, Gender='female', _2=58, _3=70, _4=68)
Pandas(Index=248, Gender='female', _2=65, _3=64, _4=62)
Pandas(Index=249, Gender='male', _2=68, _3=60, _4=53)
Pandas(Index=250, Gender='male', _2=47, _3=49, _4=49)
Pandas(Index=251, Gender='female', _2=71, _3=83, _4=83)
Pandas(Index=252, Gender='female', _2=60, _3=70, _4=70)
Pandas(Index=253, Gender='male', _2=80, _3=80, _4=72)
Pandas(Index=254, Gender='male', _2=54, _3=52, _4=52)
Pandas(Index=255, Gender='female', _2=62, _3=73, _4=70)
Pandas(Index=256, Gender='female', _2=64, _3=73, _4=68)
Pandas(Index=257, Gender='male', _2=78, _3=77, _4=77)
Pandas(Index=258, Gender='female', _2=70, _3=75, _4=78)
Pandas(Index=259, Gender='female', _2=65, _3=81, _4=81)
Pandas(Index=260, Gender='female', _2=64, _3=79, _4=77)
Pandas(Index=261, Gender='male', _2=79, _3=79, _4=78)
Pandas(Index=262, Gender='female', _2=44, _3=50, _4=51)
Pandas(Index=263, Gender='female', _2=99, _3=93, _4=90)
Pandas(Index=264, Gender='male', _2=76, _3=73, _4=68)
Pandas(Index=265, Gender='male', _2=59, _3=42, _4=41)
Pandas(Index=266, Gender='female', _2=63, _3=75, _4=81)
Pandas(Index=267, Gender='female', _2=69, _3=72, _4=77)
Pandas(Index=268, Gender='female', _2=88, _3=92, _4=95)
Pandas(Index=269, Gender='female', _2=71, _3=76, _4=70)
Pandas(Index=270, Gender='male', _2=69, _3=63, _4=61)
Pandas(Index=271, Gender='male', _2=58, _3=49, _4=42)
Pandas(Index=272, Gender='female', _2=47, _3=53, _4=58)
Pandas(Index=273, Gender='female', _2=65, _3=70, _4=71)
Pandas(Index=274, Gender='male', _2=88, _3=85, _4=76)
Pandas(Index=275, Gender='male', _2=83, _3=78, _4=73)
Pandas(Index=276, Gender='female', _2=85, _3=92, _4=93)
Pandas(Index=277, Gender='female', _2=59, _3=63, _4=75)
Pandas(Index=278, Gender='female', _2=65, _3=86, _4=80)
Pandas(Index=279, Gender='male', _2=73, _3=56, _4=57)
Pandas(Index=280, Gender='male', _2=53, _3=52, _4=42)
Pandas(Index=281, Gender='male', _2=45, _3=48, _4=46)
Pandas(Index=282, Gender='female', _2=73, _3=79, _4=84)
Pandas(Index=283, Gender='female', _2=70, _3=78, _4=78)
Pandas(Index=284, Gender='female', _2=37, _3=46, _4=46)
Pandas(Index=285, Gender='male', _2=81, _3=82, _4=82)
Pandas(Index=286, Gender='male', _2=97, _3=82, _4=88)
Pandas(Index=287, Gender='female', _2=67, _3=89, _4=82)
Pandas(Index=288, Gender='male', _2=88, _3=75, _4=76)
Pandas(Index=289, Gender='male', _2=77, _3=76, _4=77)
Pandas(Index=290, Gender='male', _2=76, _3=70, _4=68)
Pandas(Index=291, Gender='male', _2=86, _3=73, _4=70)
Pandas(Index=292, Gender='male', _2=63, _3=60, _4=57)
Pandas(Index=293, Gender='female', _2=65, _3=73, _4=75)
Pandas(Index=294, Gender='male', _2=78, _3=77, _4=80)
Pandas(Index=295, Gender='male', _2=67, _3=62, _4=60)
Pandas(Index=296, Gender='male', _2=46, _3=41, _4=43)
Pandas(Index=297, Gender='male', _2=71, _3=74, _4=68)
Pandas(Index=298, Gender='male', _2=40, _3=46, _4=50)
Pandas(Index=299, Gender='male', _2=90, _3=87, _4=75)
Pandas(Index=300, Gender='male', _2=81, _3=78, _4=81)
Pandas(Index=301, Gender='male', _2=56, _3=54, _4=52)
Pandas(Index=302, Gender='female', _2=67, _3=84, _4=81)
Pandas(Index=303, Gender='male', _2=80, _3=76, _4=64)
Pandas(Index=304, Gender='female', _2=74, _3=75, _4=83)
Pandas(Index=305, Gender='male', _2=69, _3=67, _4=69)
Pandas(Index=306, Gender='male', _2=99, _3=87, _4=81)
Pandas(Index=307, Gender='male', _2=51, _3=52, _4=44)
Pandas(Index=308, Gender='female', _2=53, _3=71, _4=67)
Pandas(Index=309, Gender='female', _2=49, _3=57, _4=52)
Pandas(Index=310, Gender='female', _2=73, _3=76, _4=80)
Pandas(Index=311, Gender='male', _2=66, _3=60, _4=57)
Pandas(Index=312, Gender='male', _2=67, _3=61, _4=68)
Pandas(Index=313, Gender='female', _2=68, _3=67, _4=69)
Pandas(Index=314, Gender='female', _2=59, _3=64, _4=75)
Pandas(Index=315, Gender='male', _2=71, _3=66, _4=65)
Pandas(Index=316, Gender='female', _2=77, _3=82, _4=91)
Pandas(Index=317, Gender='male', _2=83, _3=72, _4=78)
Pandas(Index=318, Gender='male', _2=63, _3=71, _4=69)
Pandas(Index=319, Gender='female', _2=56, _3=65, _4=63)
Pandas(Index=320, Gender='female', _2=67, _3=79, _4=84)
Pandas(Index=321, Gender='female', _2=75, _3=86, _4=79)
Pandas(Index=322, Gender='female', _2=71, _3=81, _4=80)
Pandas(Index=323, Gender='female', _2=43, _3=53, _4=53)
Pandas(Index=324, Gender='female', _2=41, _3=46, _4=43)
Pandas(Index=325, Gender='female', _2=82, _3=90, _4=94)
Pandas(Index=326, Gender='male', _2=61, _3=61, _4=62)
Pandas(Index=327, Gender='male', _2=28, _3=23, _4=19)
Pandas(Index=328, Gender='male', _2=82, _3=75, _4=77)
Pandas(Index=329, Gender='female', _2=41, _3=55, _4=51)
Pandas(Index=330, Gender='male', _2=71, _3=60, _4=61)
Pandas(Index=331, Gender='male', _2=47, _3=37, _4=35)
Pandas(Index=332, Gender='male', _2=62, _3=56, _4=53)
Pandas(Index=333, Gender='male', _2=90, _3=78, _4=81)
Pandas(Index=334, Gender='female', _2=83, _3=93, _4=95)
Pandas(Index=335, Gender='female', _2=61, _3=68, _4=66)
Pandas(Index=336, Gender='male', _2=76, _3=70, _4=69)
Pandas(Index=337, Gender='male', _2=49, _3=51, _4=43)
Pandas(Index=338, Gender='female', _2=24, _3=38, _4=27)
Pandas(Index=339, Gender='female', _2=35, _3=55, _4=60)
Pandas(Index=340, Gender='male', _2=58, _3=61, _4=52)
Pandas(Index=341, Gender='female', _2=61, _3=73, _4=63)
Pandas(Index=342, Gender='female', _2=69, _3=76, _4=74)
Pandas(Index=343, Gender='male', _2=67, _3=72, _4=67)
Pandas(Index=344, Gender='male', _2=79, _3=73, _4=67)
Pandas(Index=345, Gender='female', _2=72, _3=80, _4=75)
Pandas(Index=346, Gender='male', _2=62, _3=61, _4=57)
Pandas(Index=347, Gender='female', _2=77, _3=94, _4=95)
Pandas(Index=348, Gender='male', _2=75, _3=74, _4=66)
Pandas(Index=349, Gender='male', _2=87, _3=74, _4=76)
Pandas(Index=350, Gender='female', _2=52, _3=65, _4=69)
Pandas(Index=351, Gender='male', _2=66, _3=57, _4=52)
Pandas(Index=352, Gender='female', _2=63, _3=78, _4=80)
Pandas(Index=353, Gender='female', _2=46, _3=58, _4=57)
Pandas(Index=354, Gender='female', _2=59, _3=71, _4=70)
Pandas(Index=355, Gender='female', _2=61, _3=72, _4=70)
Pandas(Index=356, Gender='male', _2=63, _3=61, _4=61)
Pandas(Index=357, Gender='female', _2=42, _3=66, _4=69)
Pandas(Index=358, Gender='male', _2=59, _3=62, _4=61)
Pandas(Index=359, Gender='female', _2=80, _3=90, _4=89)
Pandas(Index=360, Gender='female', _2=58, _3=62, _4=59)
Pandas(Index=361, Gender='male', _2=85, _3=84, _4=78)
Pandas(Index=362, Gender='female', _2=52, _3=58, _4=58)
Pandas(Index=363, Gender='female', _2=27, _3=34, _4=32)
Pandas(Index=364, Gender='male', _2=59, _3=60, _4=58)

In [6]:
for row in df.itertuples():
    print(row.Gender)

female
female
female
male
male
female
female
male
male
female
male
male
female
male
female
female
male
female
male
female
male
female
male
female
male
male
male
female
male
female
female
female
female
male
male
male
female
female
female
male
male
female
female
male
female
male
female
female
female
male
male
male
male
male
female
female
female
male
male
female
male
male
male
female
female
male
male
female
male
female
female
male
female
male
male
male
male
male
female
female
female
male
male
male
male
female
female
female
female
female
female
male
male
male
female
male
male
female
female
female
male
male
female
male
male
female
female
male
female
female
female
male
male
female
female
male
female
female
female
female
female
male
female
male
male
female
male
male
male
female
male
male
male
female
male
male
male
male
female
male
female
female
female
male
male
female
male
male
female
male
male
male
female
male
male
female
female
male
female
male
male
female
male
male
female
female
male
female
female
female
male
male
female
female
female
female
female
female
female
female
male
female
female
female
male
male
male
male
male
female
female
male
female
male
female
male
male
male
female
female
female
female
male
female
male
male
male
male
female
female
male
male
female
male
male
male
female
female
male
male
female
male
female
male
female
female
female
male
male
female
male
male
female
male
male
male
male
female
male
male
male
female
female
male
male
male
male
female
female
male
male
female
female
male
male
female
female
male
female
female
female
male
female
female
male
male
female
female
female
female
male
male
female
female
male
male
female
female
female
male
male
male
female
female
female
male
male
female
male
male
male
male
male
female
male
male
male
male
male
male
male
male
female
male
female
male
male
male
female
female
female
male
male
female
female
male
female
male
male
female
female
female
female
female
female
female
male
male
male
female
male
male
male
male
female
female
male
male
female
female
male
female
female
male
male
female
male
female
male
male
female
male
female
female
female
female
male
female
male
female
female
male
female
female
male
male
male
male
female
female
male
female
male
female
female
male
female
female
female
male
female
male
male
female
female
female
female
female
female
male
male
female
male
male
female
male
female
female
male
male
female
male
female
female
female
female
male
female
female
male
female
male
male
male
female
male
male
male
male
male
female
female
female
female
male
female
male
male
male
male
male
female
male
female
male
male
male
male
male
male
female
female
female
female
male
female
male
male
male
male
female
female
female
male
female
male
female
male
female
male
male
male
female
female
male
female
female
male
female
male
female
female
female
female
female
female
male
male
female
male
male
female
male
male
female
male
male
female
male
male
female
female
female
female
female
male
female
female
female
male
female
female
male
female
female
female
male
male
male
female
male
male
male
female
female
female
female
female
female
female
male
female
male
male
male
male
male
female
female
female
female
female
male
female
male
female
male
female
male
male
male
male
female
female
female
male
female
male
female
male
male
male
female
male
male
female
female
male
female
male
female
female
male
female
male
male
female
female
male
male
male
male
female
female
female
male
male
female
female
female
female
female
female
female
female
female
female
female
female
female
male
male
male
female
female
female
male
male
female
female
female
female
female
male
male
male
female
female
female
female
male
female
male
female
female
female
female
male
male
male
female
male
male
male
female
male
male
male
male
female
male
male
female
female
male
male
female
female
male
female
male
female
female
female
male
female
female
female
female
female
male
female
female
female
female
female
male
male
female
male
male
male
female
female
male
female
female
female
male
male
female
male
female
female
female
female
female
female
male
male
female
male
male
female
male
female
male
male
male
male
female
female
female
female
female
female
female
female
female
male
female
female
male
female
female
male
male
male
male
female
male
female
female
male
female
female
male
female
female
male
female
male
female
male
male
male
female
male
female
male
female
male
female
male
female
male
male
female
male
male
male
female
female
female
male
male
male
male
female
male
male
male
male
female
male
female
male
male
female
male
female
female
male
female
male
female
female
male
female
male
male
male
female
female
male
female
female
female
female
male
female
female
female
female
male
female
female
female
male
female
female
female
male
male
female
female
male
female
male
female
male
male
female
female
female
male
female
female
male
male
male
male
female
male
female
male
female
male
female
female
female
female
male
female
female
male
female
female
female
male
female
female
male
female
male
female
male
female
male
female
female
male
female
male
female
male
male
male
female
male
male
female
female
male
male
female
male
female
male
male
female
female
male
female
male
male
male
male
male
male
male
female
male
male
female
male
male
male
female
female
male
female
female
male
female
female
female
male
female
male
female
female
female
male
female
female
male
female
male
female
male
female
female
female
female
male
male
female
female
male
male
female
female
female
female
female
male
female
female
male
male
female
male
female
male
male
male
female
male
female
male
male
male
male
male
male
male
female
male
male
male
female
male
male
female
female
male
female
male
female
male
female
female
male
female
male
male
female
female
male
female
female
female
female
male
female
male
male
female
female
female
male
female
female
female
female
male
male
male
female
female
male
male
female
female
male
female
male
female
female
male
female
female
female
male
female
male
female
female
female

In [7]:
for row in df.itertuples():
    print(row.Math Score)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1515825438.py, line 2)

In [8]:
df.columns

Index(['Gender', 'Math Score', 'Reading Score', 'Writing Score'], dtype='object')

In [9]:
df.columns = [col.lower() for col in df]
df.columns

Index(['gender', 'math score', 'reading score', 'writing score'], dtype='object')

In [10]:
df.rename(columns={
        'math score': 'math_score', 
        'reading score': 'reading_score',
        'writing score': 'writing_score',
    }, inplace=True
)

df

     gender  math_score  reading_score  writing_score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]